# Generated by Django 5.0.6 on 2026-07-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('CODEFORCES', 'Codeforces'), ('CODECHEF', 'CodeChef'), ('LEETCODE', 'LeetCode'), ('OA', 'OA'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('statement', models.TextField(blank=True)),
                ('difficulty_rating', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SOLVED', 'Solved'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('UNTRIED', 'Untried')], default='UNTRIED', max_length=20)),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('go', 'Go'), ('other', 'Other')], default='cpp', max_length=20)),
                ('code_submitted', models.TextField(blank=True)),
                ('time_taken_minutes', models.IntegerField(blank=True, null=True)),
                ('is_core_algorithm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('parent_category', models.CharField(choices=[('DP', 'Dynamic Programming'), ('GRAPH', 'Graph'), ('LINEAR_DS', 'Linear Data Structures'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
            ],
            options={
                'ordering': ['parent_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PostMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_found', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('lesson_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postmortems', to='core.problem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatternCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=255)),
                ('recognition_trigger', models.TextField(blank=True)),
                ('core_insight', models.TextField(blank=True)),
                ('common_edge_cases', models.TextField(blank=True)),
                ('llm_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_cards', to='core.problem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('self_rating', models.IntegerField()),
                ('next_review_date', models.DateField()),
                ('pattern_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='core.patterncard')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snapshot', models.TextField(blank=True)),
                ('language', models.CharField(max_length=20)),
                ('stdin', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('actual_output', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('WrongAnswer', 'Wrong Answer'), ('RuntimeError', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('CompileError', 'Compile Error')], default='Accepted', max_length=20)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('timer_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='core.problem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='problems', to='core.topic'),
        ),
    ]
